name: Deploy Next.js App to EC2 via Docker

on:
  push:
    branches:
      - main   # deploy only when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to app folder
            mkdir -p ~/apps/cloudlem-web
            cd ~/apps/cloudlem-web

            # Stop & remove old container if running
            docker stop cloudlem-app || true
            docker rm cloudlem-app || true

            # Clean old image
            docker rmi cloudlem-web:latest || true

            # Pull latest code
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }} .
            else
              git reset --hard
              git pull origin main
            fi

            # Build new Docker image
            docker build -t cloudlem-web .

            # Run new container
            docker run -d -p 3000:3000 --name cloudlem-app cloudlem-web
