name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp -r .next deployment/
        cp -r public deployment/
        cp -r app deployment/
        cp -r components deployment/
        cp -r lib deployment/
        cp -r hooks deployment/
        cp -r styles deployment/
        cp package*.json deployment/
        cp next.config.mjs deployment/
        cp tsconfig.json deployment/
        cp postcss.config.mjs deployment/
        cp components.json deployment/
        cp -r .next/static deployment/.next/
        tar -czf deployment.tar.gz -C deployment .

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT || 22 }}
        script: |
          # Create app directory if it doesn't exist
          sudo mkdir -p /var/www/cloudlem-landing
          cd /var/www/cloudlem-landing
          
          # Stop existing services
          sudo systemctl stop cloudlem-landing || true
          sudo docker-compose down || true
          
          # Clean up old deployment
          sudo rm -rf .next public app components lib hooks styles package*.json next.config.mjs tsconfig.json postcss.config.mjs components.json

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT || 22 }}
        source: "deployment.tar.gz"
        target: "/var/www/cloudlem-landing/"

    - name: Extract and setup on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT || 22 }}
        script: |
          cd /var/www/cloudlem-landing
          
          # Extract deployment package
          tar -xzf deployment.tar.gz
          rm deployment.tar.gz
          
          # Install dependencies
          npm ci --production
          
          # Set proper permissions
          sudo chown -R $USER:$USER /var/www/cloudlem-landing
          sudo chmod -R 755 /var/www/cloudlem-landing
          
          # Start the application
          sudo systemctl start cloudlem-landing
          sudo systemctl enable cloudlem-landing
          
          # Also start with docker-compose if available
          sudo docker-compose up -d || true
